return function ()
	describe("Character", function()
		it("should boot", function()
			local Character = require(script.Parent)
			expect(Character).to.be.ok()
		end)
		it("should boot player", function()
			local Player = require(game.ReplicatedStorage.player)
			expect(Player).to.be.ok()
		end)
		it("should create a test pseudo player instance", function()
			local Player = require(game.ReplicatedStorage.player)
			local playerInst = Player.pseudoInstance(5)
			expect(playerInst).never.to.equal(nil)
			playerInst:Destroy()
		end)
		it("should create a test player", function()
			local Player = require(game.ReplicatedStorage.player)
			local playerInst = Player.pseudoInstance(6)
			local player = Player.fromInstance(playerInst)
			
			expect(player).never.to.equal(nil)

			playerInst:Destroy()
			player:Destroy()
		end)
		it("should build a test character", function()
			local Character = require(script.Parent)
			local Player = require(game.ReplicatedStorage.player)

			local playerInst = Player.pseudoInstance(7)
			local player = Player.fromInstance(playerInst)
			local charInst = game.StarterPlayer:WaitForChild("StarterCharacter"):Clone()
			charInst.Parent = workspace
			local character = Character.fromInstance(charInst)

			expect(character).never.to.equal(nil)

			charInst:Destroy()
			character:Destroy()
			playerInst:Destroy()
			player:Destroy()
		end)
	end)
end