[package]
name = "nightcycle/reactor"
description = "A light cold-fusion powered engine / framework for Nightcycle projects. Think of it as a 'game' instance wrapper."
version = "0.1.13"
authors = ["Nightcycle <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
# constructors
isotope = "nightcycle/isotope@1.0.x"
checkbox = "nightcycle/checkbox@0.1.2"
iconlabel = "nightcycle/iconlabel@^0.1.2"
player = "nightcycle/player@0.1.2"
radiobutton = "nightcycle/radio-button@0.1.2"
switch = "nightcycle/switch@0.1.2"
textlabel = "nightcycle/textlabel@0.1.1"

# services
import = "vocksel/import@2.1.0"
draw = "nightcycle/draw@1.0.x"
enum = "nightcycle/enum@0.1.x"
fire = "nightcycle/fire@0.1.x"
format = "nightcycle/format@0.1.x"
string = "nightcycle/string@0.1.x"
texture = "nightcycle/texture@0.1.2"
query = "nightcycle/query@0.1.x"
timesync = "nightcycle/timesync@0.1.x"
voxel = "nightcycle/voxel@0.1.x"
coldfusion = "nightcycle/cold-fusion@1.0.3"
math = "nightcycle/math@2.1.x"
testez = "roblox/testez@0.4.1"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
