[package]
name = "nightcycle/reactor"
description = "A light fusion powered engine / framework for Nightcycle projects."
version = "0.1.0"
authors = ["Nightcycle <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
coldfusion = "nightcycle/cold-fusion@1.0.1"
draw = "nightcycle/draw@^1.0.0"
math = "nightcycle/math@^2.1.0"
testez = "roblox/testez@0.4.1"
isotope = "nightcycle/isotope@1.0.0"