[package]
name = "nightcycle/reactor"
description = "A light cold-fusion powered engine / framework for Nightcycle projects. Think of it as a 'game' instance wrapper."
version = "0.1.20"
authors = ["Nightcycle <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
isotope = "nightcycle/isotope@1.1.15"
player = "nightcycle/player@0.1.3"
draw = "nightcycle/draw@1.0.0"
enum = "nightcycle/enum@0.1.0"
format = "nightcycle/format@0.1.2"
string = "nightcycle/string@0.1.0"
texture = "nightcycle/texture@0.1.3"
query = "nightcycle/query@0.1.1"
timesync = "nightcycle/timesync@0.1.0"
coldfusion = "nightcycle/cold-fusion@1.0.19"
math = "nightcycle/math@2.2.1"
effect = "nightcycle/effect@1.0.0"
synthetic = "nightcycle/synthetic@3.0.11"
valuesequence = "nightcycle/valuesequence@1.1.0"
fetchu = "nightcycle/fetchu@1.0.1"
import = "vocksel/import@2.1.0"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
gui3d = "nightcycle/gui-3d@1.0.0"
